
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - net
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB_NAME}
    networks:
      - net
    restart: always
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    container_name: learning-p-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/${MONGODB_DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - net
    restart: always

volumes:
    mongo-data:
      driver: local


networks:
  net:
    driver: bridge